version: '3.4'

services:
  zlcdiscordbot:
    image: zlcbotcore:1.0.4
    container_name: zlconlinebot
    restart: unless-stopped
    build:
      context: .
      dockerfile: ZLCBotCore/Dockerfile
    volumes:
      - /home/zlcbot/botlogs:/app/logs/
